-- Nexus Elite Club - Supabase SQL Schema Initialization
-- Copy this block and run it in your Supabase SQL Editor.

CREATE TABLE "Users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" text UNIQUE NOT NULL,
    "password" text NOT NULL,
    "fullName" text,
    "role" text DEFAULT 'member',
    "tier" text,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE "Applications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fullName" text,
    "email" text,
    "mobile" text,
    "country" text,
    "companyName" text,
    "turnover" text,
    "linkedin" text,
    "membershipType" text,
    "tierSelection" text,
    "status" text DEFAULT 'Pending',
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Demo Admin User
-- NOTE: In production, do not insert raw hashed passwords directly like this if using Supabase Auth.
-- But since we are strictly maintaining our own Node.js JWT logic over Supabase, this is perfect.
-- Password inserted below is the bcrypt hash for 'admin123'
INSERT INTO "Users" ("email", "password", "fullName", "role", "tier") 
VALUES ('admin@nexuselite.club', '$2b$10$/7qMOKqZfQZ4XIZweXvQgu/vo2LNW1z6ur7vYfFgGFaZJGhh431D.', 'Nexus Admin', 'admin', 'System');

-- Password inserted below is the bcrypt hash for 'member123'
INSERT INTO "Users" ("email", "password", "fullName", "role", "tier") 
VALUES ('demo@example.com', '$2b$10$IUGj06D4IwldAhw2WkWZreSwibFt2vHlre34XuzQdaJcz/canBRQa', 'Alexander Vance', 'member', 'Billionaire');
